### PR TITLE
Statistics vue3

### PR DESCRIPTION
**Pull request by jundymek**
Here is basic desktop look for statistics section. Please correct my mistakes.

Screenshot 2021-04-26 at 09 27 47

### CODE REVIEW

**Comment by AlenJakob** [comment]
I see three(3) same components (StatisticsCard), maybe there is better way to generate them by using v-for.

Let me know what you think about this.

**Comment by jundymek** [comment]
> I see three(3) same components (StatisticsCard), maybe there is better way to generate them by using v-for.
> 
> Let me know what you think about this.

I think it was good idea. I created `const cards` that contains array of cards objects. Thanks to that I moved data into `scripts` section. I think code is more readable now and better for editing in the future.

**Comment by AlenJakob** [comment]
Nice !,

I think is not neccesery But 👍 

For example for generating a list with products is good to use v-for because when comes 100 records it will be automaticly added.

In this case is good for training vue.js :)

**Comment by jundymek** [comment]
Screenshot 2021-04-27 at 23 47 58

Mobile look.

**Comment by abioveprincipium** [comment]
I’m satisfied with the final results. I see no other obstacles to merge this components.

**Pull request merged**
